bfenetworks/bfe

bfe_config/bfe_tls_conf/server_cert_conf/server_cert_conf_load.go

append_replace_for_loop

---

bfe_basic/condition/parser/ast.go

strings.ToUpper(b.Value) == "TRUE"

simpler-to-bool

---

bfe_module/bfe_callback.go
bfe_module/bfe_handler_list.go
bfe_module/bfe_module.go
bfe_modules/mod_access/mod_access.go
bfe_modules/mod_auth_basic/mod_auth_basic.go
bfe_modules/mod_auth_basic/mod_auth_basic_test.go
bfe_modules/mod_block/mod_block.go
bfe_modules/mod_block/mod_block_test.go
bfe_modules/mod_compress/mod_compress.go
bfe_modules/mod_errors/mod_errors.go
bfe_modules/mod_geo/mod_geo.go
bfe_modules/mod_header/mod_header.go
bfe_modules/mod_header/mod_header_test.go
bfe_modules/mod_http_code/mod_http_code.go
bfe_modules/mod_key_log/mod_key_log.go
bfe_modules/mod_logid/mod_logid.go
bfe_modules/mod_redirect/mod_redirect.go
bfe_modules/mod_redirect/mod_redirect_test.go
bfe_modules/mod_rewrite/mod_rewrite.go
bfe_modules/mod_static/mod_static.go
bfe_modules/mod_static/mod_static_test.go
bfe_modules/mod_trust_clientip/mod_trust_clientip.go
bfe_server/http_conn.go
bfe_server/reverseproxy.go
bfe_server/server_status.go
bfe_server/web_server.go
go.mod
go.sum

rename consts and fix typo according to Golang Style

rename consts and fix typo mainly in bfe_module

---

docs/zh_cn/monitor/proxy_XXX_delay.md

--test=develop

---

bfe_proxy/conn_test.go
bfe_util/byte_pool/byte_pool_test.go
bfe_util/byte_pool/fixed_byte_pool_test.go
bfe_util/copy_util_test.go
bfe_util/hash_set/node_pool_test.go
bfe_util/ipdict/txt_load/txt_info.go
go.mod
go.sum

use bytes.Equal instead of bytes.Compre according to Go Style Guide

use bytes.Equal instead of bytes.Compare

---

Makefile
bfe_balance/bal_table.go

https://github.com/baidu/bfe/issues/22

Optimize lock of baltable

---

bfe_modules/mod_access/request_log.go

Remove redundant fmt.Sprintf in bfe_modules/mod_access/request_log.go

---

bfe_util/ipdict/ip_loc_table.go
bfe_util/ipdict/txt_load/txt_info.go

parameters should not be capitalized.

rename some parameters in bfe_util/ipdict

---

docs/en_us/condition/request/header.md

update markdown 

---

bfe_modules/mod_logid/mod_logid.go
go.mod
go.sum

mod_logid: simplify Init  and  afterLocation func

需求：修改及简化 mod_logid

---

bfe_modules/mod_logid/mod_logid.go
bfe_modules/mod_redirect/mod_redirect.go

Change callback point from HandleAfterLocation to HandleFoundProduct

mod_redirect: change callback point #228

---

docs/zh_cn/reload.md

update reload.md's table

---

bfe_modules/bfe_modules.go
bfe_modules/mod_userid/conf_mod_userid.go
bfe_modules/mod_userid/conf_mod_userid_test.go
bfe_modules/mod_userid/mod_userid.go
bfe_modules/mod_userid/mod_userid_test.go
bfe_modules/mod_userid/testdata/mod_userid/mod_userid.conf
bfe_modules/mod_userid/testdata/mod_userid/mod_userid_default.conf
bfe_modules/mod_userid/testdata/mod_userid/userid_rule.data
bfe_modules/mod_userid/testdata/mod_userid/userid_rule_rules_empty.data
bfe_modules/mod_userid/userid_conf_load.go
bfe_modules/mod_userid/userid_conf_load_test.go
conf/bfe.conf
conf/mod_userid/mod_userid.conf
conf/mod_userid/userid_rule.data

Add mod_userid (#75)

---

bfe_modules/mod_prison/rules.go

delete unused `lock     sync.Mutex` in `struct prisonRules`

delete useless lock

---

bfe_module/bfe_plugin.go
docs/en_us/configuration/config.md
docs/en_us/faq/installation.md
docs/zh_cn/configuration/config.md
docs/zh_cn/module/bfe_callback.md

change BFEVersion to bfeVersion , delete useless annotation and update error log

optimize bfe_plugin.go

---

bfe_modules/bfe_modules.go
bfe_modules/mod_auth_jwt/config/auth_config.go
bfe_modules/mod_auth_jwt/config/auth_config_test.go
bfe_modules/mod_auth_jwt/config/config.go
bfe_modules/mod_auth_jwt/config/config_test.go
bfe_modules/mod_auth_jwt/config/module_config.go
bfe_modules/mod_auth_jwt/config/module_config_test.go
bfe_modules/mod_auth_jwt/config/product_config.go
bfe_modules/mod_auth_jwt/config/product_config_test.go
bfe_modules/mod_auth_jwt/jwt/jwe.go
bfe_modules/mod_auth_jwt/jwt/jwe_test.go
bfe_modules/mod_auth_jwt/jwt/jws.go
bfe_modules/mod_auth_jwt/jwt/jwt.go
bfe_modules/mod_auth_jwt/jwt/jwt_test.go
bfe_modules/mod_auth_jwt/mod_auth_jwt.go
bfe_modules/mod_auth_jwt/mod_auth_jwt_test.go

Accept suggestions from PR #403

mode_auth_jwt: Code optimization (Suggestions from PR#403)

---

bfe_basic/condition/primitive.go

remove function "contains"

---

bfe_config/bfe_tls_conf/session_ticket_key_conf/session_ticket_key_conf.go

update RAW_SESSION_TICKET_KEY_SIZE to RawSessionTicketKeySize

update RAW_SESSION_TICKET_KEY_SIZE to RawSessionTicketKeySize

---

bfe_basic/action/action.go
bfe_basic/action/action_host.go
bfe_modules/mod_rewrite/action.go

Add HostSuffixReplace action in mod_rewrite (#451)

---

docs/en_us/modules/mod_rewrite/mod_rewrite.md

需求10: 更新 mod_rewrite 文档(英文)
在HOST_SET_FROM_PATH_PREFIX下一行增加：
HOST_SUFFIX_REPLACE Replace suffix of host

Update en_us mod_rewrite.md

---

docs/en_us/condition/request/header.md

Update en_us header.md

---

docs/en_us/condition/request/cookie.md
docs/en_us/condition/request/header.md
docs/en_us/condition/request/ip.md
docs/en_us/condition/request/method.md
docs/en_us/condition/request/protocol.md
docs/en_us/condition/request/tag.md
docs/en_us/condition/request/uri.md

需求11：
把每个文档的标题改为 首字母大写，把最有一个单词 primitive改为复数，即 Request Cookie Related Primitives

Update en_us request/

---

docs/material/overrides/home_en.html
docs/material/overrides/home_zh.html

Optimize layout and add icon

---

docs/material/overrides/home_en.html
docs/material/overrides/home_zh.html

Add describe

---

docs/Makefile
docs/material/overrides/home_en.html
docs/material/overrides/home_zh.html

Update picture path and Makefile

Update picture path and Makefile

---

Dockerfile

Updated to latest release of golang 1.13

Updated dockerfile to 1.13.11

---

bfe_modules/mod_trust_clientip/mod_trust_clientip.go

%s -> %t for session.IsTrustIP

fix format verbs for boolean

---

bfe_server/bfe_server.go

Unify receiver name of BfeServer

---

bfe_modules/mod_geo/mod_geo.go
bfe_modules/mod_header/mod_header.go
bfe_modules/mod_redirect/mod_redirect.go
bfe_modules/mod_rewrite/mod_rewrite.go

fix-format-verbs

---

bfe_module/bfe_callback.go

fix handler type bug

---

docs/material/overrides/home_en.html
docs/material/overrides/home_zh.html

change Footers information

---

bfe_balance/backend/bfe_backend.go
bfe_balance/bal_slb/bal_rr_test.go
bfe_server/http_conn.go
bfe_server/reverseproxy.go
bfe_stream/server_conn.go
bfe_websocket/server_conn.go

- use consistent var name style: xxxNum
- use IncXxxNum to correspond to DecXxxNum
- fix typos in comment

tweak variable name and comment

---

bfe_modules/bfe_modules.go
bfe_modules/mod_markdown/conf_mod_md.go
bfe_modules/mod_markdown/conf_mod_md_test.go
bfe_modules/mod_markdown/md_render.go
bfe_modules/mod_markdown/md_render_test.go
bfe_modules/mod_markdown/md_rule_load.go
bfe_modules/mod_markdown/md_rule_load_test.go
bfe_modules/mod_markdown/md_rule_table.go
bfe_modules/mod_markdown/md_rule_table_test.go
bfe_modules/mod_markdown/mod_markdown.go
bfe_modules/mod_markdown/mod_markdown_test.go
bfe_modules/mod_markdown/testdata/case0/mod_markdown/mod_markdown.conf
bfe_modules/mod_markdown/testdata/case1/mod_markdown/mod_markdown.conf
bfe_modules/mod_markdown/testdata/case1/mod_markdown/mod_markdown.data
bfe_modules/mod_markdown/testdata/mod_markdown.conf
bfe_modules/mod_markdown/testdata/mod_markdown.data
bfe_modules/mod_markdown/testdata/mod_markdown/mod_markdown.conf
bfe_modules/mod_markdown/testdata/mod_md_invalid_action.data
bfe_modules/mod_markdown/testdata/mod_md_invalid_cond.data
bfe_modules/mod_markdown/testdata/mod_md_noversion.data
bfe_modules/mod_markdown/testdata/testcase0.md
bfe_modules/mod_markdown/testdata/testcase0.output
bfe_modules/mod_markdown/testdata/testcase0_default.output
bfe_modules/mod_markdown/testdata/testcase1.md
bfe_modules/mod_markdown/testdata/testcase1_default.output
conf/mod_markdown/mod_markdown.conf
conf/mod_markdown/mod_markdown.data
go.mod

mod_markdown to process markdown response

add markdown render, if rep is text/markdown, render the md to html

---

bfe_net/textproto/reader.go
bfe_net/textproto/reader_test.go

fix header problem: what if whitespace in header

---

.goreleaser.yml

Updated the .goreleaser.yml file to generate linux/arm64 release for bfe.
Signed-off-by: odidev <odidev@puresoftware.com>

Added arm64 support to .goreleaser.yml

---

bfe_modules/bfe_modules.go
bfe_modules/mod_secure_link/checker.go
bfe_modules/mod_secure_link/checker_test.go
bfe_modules/mod_secure_link/conf_load.go
bfe_modules/mod_secure_link/conf_load_test.go
bfe_modules/mod_secure_link/data_load.go
bfe_modules/mod_secure_link/data_load_test.go
bfe_modules/mod_secure_link/mod_secure_link.go
bfe_modules/mod_secure_link/mod_secure_link_test.go
bfe_modules/mod_secure_link/prodcut_table.go
bfe_modules/mod_secure_link/product_table_test.go
bfe_modules/mod_secure_link/testdata/mod_secure_link/mod_secure_link.conf
bfe_modules/mod_secure_link/testdata/mod_secure_link/secure_link_rule.data
bfe_modules/mod_secure_link/testdata/mod_secure_link/secure_link_rule1.data

feat: mod_secure_link

---

bfe_modules/mod_userid/mod_userid.go
bfe_modules/mod_userid/testdata/mod_userid/userid_rule.data

fix: fix domain of mod_userid

---

bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go
bfe_config/bfe_cluster_conf/cluster_table_conf/cluster_table_load.go
bfe_config/bfe_cluster_conf/gslb_conf/gslb_conf_load.go
go.mod

bfe use ffjson in wrong way which make ffjson just use econding/json to decode json fail;
change ffjson to github.com/json-iterator/go

fix ffjson use error

---

bfe_modules/mod_rewrite/action.go
bfe_modules/mod_rewrite/rewrite_conf_load.go

add rewrite rule cmd check

---

bfe_net/textproto/reader.go

add some tips for NewReader

---

.github/workflows/ci.yml
bfe_net/textproto/reader.go

add simple Test to ensure bfe runs ok

support Test in CI

---

bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go
bfe_fcgi/common.go
bfe_fcgi/fcgi_client.go
bfe_fcgi/transport.go
bfe_route/bfe_cluster/bfe_cluster.go
bfe_server/reverseproxy.go
conf/cluster_conf/cluster_table.data
conf/cluster_conf/gslb.data
conf/server_data_conf/cluster_conf.data
conf/server_data_conf/host_rule.data
conf/server_data_conf/route_rule.data

feat: fastcgi, without conn pool, timeout control

---

bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go

Signed-off-by: liuximu <295421489@qq.com>

remove useless ClusterProtocol

---

README.md
docs/en_us/configuration/server_data_conf/cluster_conf.data.md
docs/en_us/introduction/overview.md
docs/material/overrides/home_en.html
docs/material/overrides/home_zh.html
docs/zh_cn/configuration/server_data_conf/cluster_conf.data.md
docs/zh_cn/introduction/overview.md

Signed-off-by: liuximu <295421489@qq.com>

doc: doc for fastcgi

---

bfe_bufio/bufio_test.go

fix issue: https://github.com/bfenetworks/bfe/issues/633
detail see: https://github.com/golang/go/issues/32479

Convert int to string using rune(), fix issue #633

---

bfe_modules/mod_header/action_header_var.go

format code style

---

docs/material/overrides/home_en.html
docs/material/overrides/home_zh.html

Add anchor

---

bfe_basic/condition/parser/ast.go

edit code style

---

Dockerfile
docs/en_us/installation/install.md
docs/en_us/installation/install_using_docker.md
docs/zh_cn/installation/install.md
docs/zh_cn/installation/install_using_docker.md

Signed-off-by: liuximu <295421489@qq.com>

doc: docker install

---

docs/en_us/SUMMARY.md
docs/en_us/example/fastcgi.md
docs/zh_cn/SUMMARY.md
docs/zh_cn/example/fastcgi.md

Signed-off-by: liuximu <295421489@qq.com>

doc: fastcgi example

---

bfe_basic/condition/build.go
bfe_basic/condition/parser/semant.go
bfe_basic/condition/primitive.go
bfe_basic/condition/primitive_test.go

support issues=#653

---

bfe_util/signal_table/signal_table.go

Receiver Consistent

---

docs/material/overrides/home_en.html
docs/material/overrides/home_zh.html
docs/mkdocs_en.yml
docs/mkdocs_zh.yml

Update copyright date

---

bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go
bfe_server/reverseproxy.go

fix timeout bug in some hook point.

fix timeout bug in some hook point

---

bfe_balance/backend/bfe_backend.go
bfe_balance/backend/health_check.go
bfe_balance/bal_gslb/bal_gslb.go
bfe_balance/bal_gslb/bal_gslb_test.go
bfe_balance/bal_gslb/sub_cluster.go
bfe_balance/bal_slb/backend_rr.go
bfe_balance/bal_slb/backend_rr_test.go
bfe_balance/bal_slb/bal_rr.go
bfe_balance/bal_slb/bal_rr_test.go
bfe_balance/bal_table.go
bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go
bfe_config/bfe_cluster_conf/cluster_conf/testdata/cluster_conf_1.conf
bfe_server/bfe_confdata_load.go

Hi guys,
I made a feature to support slow_start when instances restart.
Please have a look if this is good for bfe.
I've already verified in my private environment.
thanks.

support slow_start feature

---

docs/en_us/configuration/server_data_conf/cluster_conf.data.md
docs/zh_cn/configuration/server_data_conf/cluster_conf.data.md

add maxConnsPerHost to  cluster config docs

add maxConnsPerHost to  cluster config docs

---

docs/en_us/condition/condition_primitive_index.md
docs/en_us/condition/request/uri.md
docs/zh_cn/condition/condition_primitive_index.md
docs/zh_cn/condition/request/uri.md

add req_path_contain doc

---

bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go
docs/en_us/configuration/server_data_conf/cluster_conf.data.md
docs/zh_cn/configuration/server_data_conf/cluster_conf.data.md

add doc about OutlierDetectionHttpCode and delete  OutlierDetectionLevel in cluster config

add doc about OutlierDetectionHttpCode 

---

bfe_modules/mod_header/action.go
bfe_modules/mod_header/action_header.go
bfe_modules/mod_header/action_test.go
bfe_modules/mod_header/testdata/mod_header/header_rule.data

add header rename action
```json
{
"cond": "req_path_prefix_in(\"/header_rename\", false)",
"actions": [
{
"cmd": "REQ_HEADER_RENAME",
"params": [
"OriginalKey",
"NewKey"
]
}
],
"last": true
},
```
#683 

mod_header: add header renaming actions #683

---

bfe_modules/mod_header/action.go

fix code style

---

bfe_net/textproto/pipeline.go

sync golang net/textproto
#597
cp [commit1](https://github.com/golang/go/commit/7340e5a1e86311302c6fcc3a86afe7ff9cbf5e49#diff-36d62e1f92b8483bd1f63c4f8dc3a5eed52f2312fb0f9ccbaf05c5c984d348ab) and [commit2](https://github.com/golang/go/commit/4874835232322713f23d2f10c083ae6fa893868b#diff-36d62e1f92b8483bd1f63c4f8dc3a5eed52f2312fb0f9ccbaf05c5c984d348ab)

sync net/textproto modify pipline

---

.gitignore

ignore some ide config file in .gitignore.

ignore ide file

---

bfe_http/header.go
bfe_net/textproto/header.go
bfe_net/textproto/header_test.go
bfe_net/textproto/reader_test.go

sync net/textproto [commit](https://github.com/golang/go/commit/3972f97d049edde37936d8b675e3600d10705dbc)

sync net/textproto #597 sync header

---

bfe_net/textproto/reader.go

sync golang net/textproto [commit](https://github.com/golang/go/commit/f5b695030b857b079a4cbcfb79564ff933c0c8f2)

sync textproto #597

---

bfe_http2/server_test.go

fix unit test fail

---

docs/zh_cn/configuration/server_data_conf/cluster_conf.data.md
docs/zh_cn/development/local_dev_guide.md

"wody"->"body"
"单侧"->"单测"
test=develop

"wody"->"body"

---

bfe_http/cookie.go

sync golang http cookie
[commit](https://github.com/golang/go/commit/6b7114b9e5d872fe981a5c988915e4440f8df59c#diff-943a3a83d1926a51599e123e0400e00a5352d520638f1d248c22267ad74bd6e8)

sync golang/go http cookie

---

bfe_http/cookie.go
bfe_http/cookie_test.go

sync golang/go [commit](https://github.com/golang/go/commit/68998433556a5c9ee0f7d8d544ffb006a724adaf)

sync golang go http cookie  optimize internal cookie functions

---

bfe_server/reverseproxy.go

Signed-off-by: yangqingxin1993 <yangqingxin@baidu.com>

fix panic when write client timeout

---

bfe_modules/mod_access/conf_mod_access.go
bfe_modules/mod_access/mod_access.go
bfe_modules/mod_key_log/conf_mod_key_log.go
bfe_modules/mod_key_log/mod_key_log.go
bfe_modules/mod_waf/conf_mod_waf.go
bfe_modules/mod_waf/conf_mod_waf_test.go
bfe_modules/mod_waf/waf_log.go
bfe_util/access_log/access_log.go
bfe_util/access_log/access_log_test.go
docs/en_us/modules/mod_access/mod_access.md
docs/en_us/modules/mod_key_log/mod_key_log.md
docs/zh_cn/modules/mod_access/mod_access.md
docs/zh_cn/modules/mod_key_log/mod_key_log.md
go.mod
go.sum

 support log to single file

---

bfe_http/cookie.go
bfe_http/cookie_test.go

sync golang [commit](https://github.com/golang/go/commit/d86a6ef0c7e8307802c6cd3f623bade3e78a42bf#diff-943a3a83d1926a51599e123e0400e00a5352d520638f1d248c22267ad74bd6e8)

sync golang http/cookie validCookieExpires

---

bfe_balance/bal_gslb/bal_gslb.go
bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go

source from bfe-pro-20: 支持基于URL哈希的负载均衡算法

hash support requestURI

---

bfe_modules/mod_block/action.go
bfe_modules/mod_block/mod_block.go
bfe_modules/mod_block/testdata/block_rules_1.conf
bfe_modules/mod_block/testdata/block_rules_3.conf

support ACL's allow policy

---

docs/en_us/modules/mod_block/mod_block.md
docs/zh_cn/modules/mod_block/mod_block.md

update documents for mod_block

update doc for support ACL's allow policy

---

bfe_modules/mod_header/action_header_var.go

mod_header: support variables about client certificate

---

docs/en_us/modules/mod_header/mod_header.md
docs/zh_cn/modules/mod_header/mod_header.md

Signed-off-by: zhangxiaogang01 <zhangxiaogang01@baidu.com>

upate mod_header.md

---

bfe_basic/condition/build.go
bfe_basic/condition/parser/semant.go
bfe_basic/condition/primitive.go
bfe_basic/condition/primitive_test.go

support time_range

---

bfe_basic/condition/primitive.go
docs/en_us/condition/condition_primitive_index.md
docs/en_us/condition/system/time.md
docs/zh_cn/condition/condition_primitive_index.md
docs/zh_cn/condition/system/time.md

add doc for periodic_time_range

add doc for periodic_time_range

---

bfe_basic/condition/build.go
bfe_basic/condition/parser/semant.go

add case_sensitive flag for req_context_value_in

add case sensitive flag for req_context_value_in

---

docs/en_us/modules/mod_http_code/mod_http_code.md

Found a typo while reading docs

Fix a typo in mod_http_code doc

---

docs/en_us/condition/request/cookie.md
docs/en_us/condition/request/header.md
docs/en_us/condition/request/ip.md
docs/en_us/condition/request/method.md
docs/en_us/condition/request/uri.md
docs/en_us/condition/response/code.md
docs/en_us/condition/response/header.md
docs/en_us/condition/session/ip.md
docs/en_us/condition/system/time.md

Found typos while reading docs

Fix Typos in doc

---

bfe_route/host_table.go
bfe_server/reverseproxy.go

lock optimization： double check

lock: double check

---

bfe_config/bfe_route_conf/route_rule_conf/route_table_load.go

Export function convert() in route_table_conf for config verification from outside.

export function in RouteTableFile for config verification

---

docs/en_us/faq/development.md
docs/zh_cn/development/write_doc_guide.md

en_us: develop a module
zh_cn: write doc guide

fix doc link

---

release_local.sh

Signed-off-by: kwanhur <huang_hua2012@163.com>

Add release local bash script's license header

---

bfe_util/copy_util.go

see https://github.com/golang/go/pull/39989
and
https://github.com/golang/go/commit/03f181a90ef4de680a666ca86c7988915e892e8c

add errInvalidWrite for CopyWithoutBuffer

---

bfe_server/http_server.go

Remove unused param rwc in http_server.go
close #912

Remove unused param rwc

---

bfe_modules/mod_tcp_keepalive/data_load.go

use json-iterator in mod_tcp_keepalive to load conf

---

bfe_basic/condition/parser/parser_test.go
bfe_http/cookie_test.go
bfe_modules/mod_prison/rule_test.go

Signed-off-by: liu-song <liusongstep@gmail.com>
https://github.com/bfenetworks/bfe/pull/931
将一些测试函数中的encoding/json替换成 json-iterator

use json-iterator replace encoding/json

---

bfe_basic/condition/primitive.go
bfe_basic/session.go
bfe_http/transfer.go
bfe_modules/mod_access/session_log.go
bfe_modules/mod_markdown/md_render.go
bfe_modules/mod_prison/data_load.go
bfe_modules/mod_prison/product_rule_table.go
bfe_modules/mod_prison/rules.go
bfe_modules/mod_waf/waf_rule_load.go
bfe_util/get_net_info.go
bfe_util/ipdict/ip_loc_table.go
bfe_util/ipdict/txt_load/txt_load.go

https://github.com/golangci/golangci-lint   可以较为全面的检查Go 代码，安装之后，运行golangci-lint run  会显示一些代码的修改建议，这个检查工具相对来说比较严格，在bfe 目前的代码里面运行会有很多提示，更多的提示是一些变量声明了，但没有使用的情况，也有一部分关于errcheck的，对返回的err 没有进行进一步判断处理的情况，这些建议目前都没有作出修改。如果有必要的话，可以再视情况做出对应的修改~

follow golangci-lint suggestions to change code

---

bfe_modules/mod_trust_clientip/mod_trust_clientip.go

it supports `IPv4` `IPv6` and solves #856

mod_trust_clientip: check remote addr private when stats

---

Makefile

- make deps add install pre-commit
- make precommit supports to autoupdate and install hooks

Feature pre-commit install with make

---

.pre-commit-config.yaml

Reverts bfenetworks/bfe#993
See：
https://github.com/bfenetworks/bfe/discussions/1013

Revert "chore: add typos in pre-commit"

---

bfe_modules/mod_geo/mod_geo.go

Signed-off-by: suhang <1099811329@qq.com>

fix geo spell err

---

bfe_http/header.go
bfe_modules/mod_redirect/action.go

setting size for new slice is to reduce resize

---

ADOPTERS.md

This pull request adds new entry in the list of adopters.
I wish every reviewer a wonderful September day with full of happiness!

Add PITS Global Data Recovery Services as adopter
