- bfe_server/bfe_server.go
- bfe_util/signal_table/register_signal.go
signal SIGSTKFLT is unused in linux and  block build on MAC, remove it.
> remove signal SIGSTKFLT.

- bfe.go
net/http/pprof 服务，默认注册至http.DefaultServeMux，在bfe server中并不起作用。后面会将pprof迁移至monitor server中。
> remove_pprof_from_bfe

- bfe_server/register_modules.go
use strings.TrimSpace to remove all leading and trailing white space
> string trim space 

- bfe_basic/condition/build.go
- bfe_basic/condition/parser/semant.go
Condition primitive: req_host_suffix_in #475
Description:
Add Condition primitive: req_host_suffix_in(suffix_list)
Example:
check the request host is a subdomain of example.com or example.org
req_host_suffix_in(".example.com|.example.org")
> Add Condition primitive: req_host_suffix_in(suffix_list)

- .github/workflows/ci.yml
I think we can support GitHub action, and instead of `travis-ci`.
And In the future, we can use GitHub action to release new versions.
for release package, can refer: https://github.com/airdb/adb/blob/master/.github/workflows/release.yml
> support github actions

- docs/zh_cn/configuration/cluster_conf/cluster_table.data.md
修改文档：实例负载均衡配置  中的拼写错误，确认仅中文版有误，英文版正确
> fix doc of cluster_table.date.md  Name mistake

- bfe_server/reverseproxy.go
If module return close in `handleForward` phase, BFE will panic cause of closing body of nil response. Detail see: [issue629](https://github.com/bfenetworks/bfe/issues/629)
> fix issue #629

- bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go
- bfe_route/bfe_cluster/bfe_cluster.go
- bfe_server/reverseproxy.go
change outlierDetectionLevel to OutlierDetectionHttpCode.
As backend config above, bfe will add backend's fail count when backend return 5xx or 404;
```json
"BackendConf": {
"TimeoutConnSrv": 50000,
"TimeoutResponseHeader": 50000,
"MaxIdleConnsPerHost": 0,
"RetryLevel": 0,
"OutlierDetectionHttpCode": "5xx|404",
},
```
> change outlierDetectionLevel to OutlierDetectionHttpCode

- bfe_config/bfe_cluster_conf/cluster_conf/cluster_conf_load.go
- bfe_http/transport.go
- bfe_server/reverseproxy.go
add maxConnPerHost
MaxConnsPerHost limit the maximum number of tcp connections sent to the backend.
```json
"BackendConf": { 
"TimeoutConnSrv": 50000,
    "TimeoutResponseHeader": 50000,
   "MaxIdleConnsPerHost": 0,
"RetryLevel": 0,
        "MaxConnsPerHost": 100 
},
```
> add maxConnPerHost

- bfe_net/textproto/reader.go
- bfe_net/textproto/reader_test.go
sycn golang/go net/textproto, [commit](https://github.com/golang/go/commit/6f772787f97720aeeb98d37b2c63b1a3155588d1)
> sync net/textproto reader trim line

- bfe_http2/server.go
- bfe_http2/server_test.go
sync from golang/net http2 [commit](https://github.com/golang/net/commit/39120d07d75e76f0079fe5d27480bcb965a21e4c)
currently bfe will send rst if the server receives data after goway. 
As describe in https://tools.ietf.org/html/rfc7540#section-6.8, BFE should do nothing when receives data after goway.
> sync http2, discard DATA frames with higher stream IDs after shutdown #450

- bfe_http2/server.go
- bfe_http2/server_test.go
#450 
sync http2 [commit](https://github.com/golang/net/commit/9ef9f5bb98a1fdc41f8cf6c250a4404b4085e389)
> sync http2, receiving too much data is a protocol error

- bfe.go
- bfe_config/bfe_conf/conf_basic.go
- go.mod
- go.sum
GOMAXPROCS needs to be set according to real CPU quota especially in container environment with CPU limit, but runtime.NumCPU() will return the CPU number of machine, which may be very large and will affect the performance. "go.uber.org/automaxprocs" can set the GOMAXPROCS according to the environment automatically.
> support setting GOMAXPROCS according to real CPU quota

- bfe_config/bfe_route_conf/route_rule_conf/basic_rule_tree.go
- bfe_config/bfe_route_conf/route_rule_conf/basic_rule_tree_test.go
- bfe_config/bfe_route_conf/route_rule_conf/route_table_load.go
- bfe_config/bfe_route_conf/route_rule_conf/route_table_load_test.go
- bfe_config/bfe_route_conf/route_rule_conf/testdata/basic_route_rule1.data
- bfe_config/bfe_route_conf/route_rule_conf/testdata/basic_route_rule2.data
- bfe_config/bfe_route_conf/route_rule_conf/testdata/basic_route_rule3.data
- bfe_config/bfe_route_conf/route_rule_conf/testdata/basic_route_rule4.data
- bfe_config/bfe_route_conf/route_rule_conf/testdata/basic_route_rule5.data
- bfe_config/bfe_route_conf/route_rule_conf/testdata/basic_route_rule6.data
- bfe_config/bfe_route_conf/route_rule_conf/testdata/basic_route_rule7.data
- bfe_route/host_table.go
- bfe_route/server_data_conf.go
- bfe_util/string_reverse/string_reverse.go
- go.mod
Add basic route rule support in bfe. Basic route rule means host+path routing, which describe how to route incoming HTTP request based on Host and Path in message header. Original route rule, based on condition expression, is renamed as advanced  route rule。
The basic host and path matching rule is same as description in k8s ingress. Please refer to  https://kubernetes.io/docs/concepts/services-networking/ingress/
> support basic route rule

- bfe_route/server_data_conf.go
Fix config checking in loading basic route rule, bypass cluster_name checking if cluster_name equals ADVANCED_MODE.
> basic rule routing, disable checking if cluster_name equals ADVANCED_MODE

- bfe_tls/handshake_server.go
use hex.EncodeToString to convert md5 result to string.
about 2x performance increase
> update md5 in TLS handshake 

- docs/en_us/configuration/server_data_conf/cluster_conf.data.md
- docs/zh_cn/configuration/server_data_conf/cluster_conf.data.md
Improve and fix error in document  cluster_conf.data.md 
1. Fix issue #833 about document
2. Correct other default value description in cluster_conf.data.md 
3. Update english version of  cluster_conf.data.md to sync up with chinese version
4. Fix other minor issues in cluster_conf.data.md 
5. Add description of below parameter back to chinese version:
"ReqWriteBufferSize": 512,
"ReqFlushInterval": 0,
"ResFlushInterval": -1,
"CancelOnClientClose": false
> Improve and fix error in cluster_conf.data.md (issue #833)

- bfe_server/bfe_server_init.go
bug `bfe launch failed when disable monitor server` was imported by #937 
solution: 
1. remove `MonitorEnable` check when `InitWebMonitor`, always do this initialization
1. monitor server doesn't startup when disable
> bugfix: start bfe monitor web server only when enable

- docs/en_us/development/module/bfe_callback.md
- docs/zh_cn/development/module/bfe_callback.md
- mark code span on function prototype, like `handler(req *bfe_basic.Request, res *bfe_http.Response) int`
> typo: code span on function prototype of bfe callback

- docs/en_us/monitor/bal_state.md
- docs/en_us/monitor/bal_table_status.md
- docs/en_us/monitor/http2_state.md
- docs/en_us/monitor/http_state.md
- docs/en_us/monitor/latency.md
- docs/en_us/monitor/module_status.md
- docs/en_us/monitor/proxy_mem_stat.md
- docs/en_us/monitor/tls_state.md
- docs/en_us/monitor/websocket_state.md
- docs/zh_cn/monitor/bal_state.md
- docs/zh_cn/monitor/module_status.md
- docs/zh_cn/monitor/proxy_state.md
- docs/zh_cn/monitor/tls_state.md
- docs/zh_cn/monitor/websocket_state.md
- trim tailing space
- remove redundant space line
- fix some words spelling error
> typo: fix docs/monitor markdown lint and syntax

- .pre-commit-config.yaml
* upgrade [pre-commit-golang](git://github.com/dnephin/pre-commit-golang) to v0.5.0
* enable `staticcheck` hook on pre-commit
related issue https://github.com/bfenetworks/bfe/issues/1017#issuecomment-1057687624
test case:
```bash
➜  bfe git:(precommit-sc) ✗ git add bfe_cli/a.go 
➜  bfe git:(precommit-sc) ✗ git cm "test check"
go fmt...................................................................Passed
go vet...................................................................Passed
go-unit-tests............................................................Passed
go-build.................................................................Passed
go staticcheck...........................................................Failed
- hook id: go-static-check
- exit code: 1
bfe_cli/a.go:3:5: var name is …
```
> chore: add staticcheck pre-commit hook

- .pre-commit-config.yaml
- Makefile
1. pre-commit hooks
* markdownlint
* markdownlint-fix
2. remove `mdlint` `mdlint-fix` target in Makefile
> ci(precommit): add markdownlint hook

- bfe_http/transport.go
`putIdleConn`时，当空闲队列中的数量大于MaxIdleConnsPerHost时，将关闭空间时间最长的连接，而不是关闭当前新创建的连接。
原因：当tcp连接空闲一段时间后，拥塞窗口将会重置，下次启动时将以慢启动开始，最近的连接会有比较大的窗口大小，相对于已经空闲一段时间的连接，能够比较快速的进行数据传输。
> 优化空闲连接>MaxIdleConnsPerHost情况下处理

- bfe_basic/action/action_query.go
- bfe_basic/condition/primitive.go
- bfe_fcgi/transport.go
- bfe_http/request_test.go
- bfe_http2/hpack/encode_test.go
- bfe_http2/hpack/hpack_test.go
- bfe_net/textproto/reader_test.go
Replace `strings.Replace(s, old, new, -1)` with `strings.ReplaceAll(s, old, new)`. `strings.ReplaceAll` is a wrapper function for `strings.Replace`, but `strings.ReplaceAll` is more readable and removes the hardcoded `-1`.
> refactor: replace strings.Replace with strings.ReplaceAll

- Makefile
fix build failed on macos #1066
> fix build failed on macos

- bfe_balance/bal_slb/bal_rr.go
- bfe_balance/bal_slb/bal_rr_test.go
Signed-off-by: likepeng <cooper_li@foxmail.com>
> make some optimization for leastConnsBalance, Benchmark increases 43%

- bfe_basic/condition/primitive_test.go
- bfe_http2/server_test.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
see https://go.dev/play/p/8fS-lKgH7Ze for example:
```go
package main
import (
"fmt"
"testing"
"time"
)
func TestA(t *testing.T) {
errc := make(chan error, 1)
donec := make(chan bool)
go func() {
defer close(donec)
time.Sleep(time.Second)
// time.Sleep(10 * time.Second) // or you want test with timeout.
}()
select {
case <-donec:
fmt.Println("just return")
return
case <-time.After(5 * time.Second):
t.Fatal("timeout")
}
fmt.Println("cant reach!!!")
e := fmt.Errorf("err one")
errc <- e
select {
case err := <-errc:
if err != nil {
t.Fatalf("Error in handler: %v", err)
}
case <-time.After(2 * time.Second):
t.Error("timeout waiting for handler to finish")
}
}
/* 
// Output:
=== RUN   TestA
just return
--- PASS: TestA (1.00s)
PASS
Program exited. …
```
> fix some unreachable code

- bfe_modules/mod_tcp_keepalive/mod_tcp_keepalive_test.go
- This unit test uses an external IP for testing.
- The service at this IP is not stable, and recently, frequent unresponsiveness has resulted in compilation failures.
- Unit tests should not rely on external services.
> remove TestSetKeepAlive

- Dockerfile
Replace go compile args to TARGETOS and TARGETARCH to support multiarch compile
> Update Dockerfile to support multiarch build

- docs/en_us/SUMMARY.md
- docs/en_us/modules/mod_wasmplugin/mod_wasmplugin.md
- docs/zh_cn/SUMMARY.md
- docs/zh_cn/modules/mod_wasmplugin/mod_wasmplugin.md
> docs of mod_wasmplugin
